# Generated by Django 4.1.4 on 2022-12-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dummydata", "0003_alter_fakeschemacolumn_data_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fakeschemacolumn",
            name="range_from",
        ),
        migrations.RemoveField(
            model_name="fakeschemacolumn",
            name="range_to",
        ),
        migrations.AlterField(
            model_name="fakeschema",
            name="title",
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name="fakeschemacolumn",
            name="data_type",
            field=models.CharField(
                choices=[
                    (
                        "Full_name",
                        "Full name (a combination of first name and last name)",
                    ),
                    ("Job", "Job"),
                    ("Email", "Email"),
                    ("Domain", "Domain name"),
                    ("Phone", "Phone number"),
                    ("Company", "Company name"),
                    ("Text", "Text (with a specified range for a number of sentences)"),
                    ("Integer", "Integer (with specified range)"),
                    ("Address", "Address"),
                    ("Date", "Date"),
                ],
                max_length=20,
            ),
        ),
    ]
